[tool.pysen]
version = "0.10.2"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = false
mypy_preset = "strict"
line_length = 88
py_version = "py37"
[tool.pysen.lint.source]
  excludes = ["config/", "images/", "tests/", "venv/"]
[[tool.pysen.lint.mypy_targets]]
  paths = ["networks", "scripts"]
[tool.pysen.lint.mypy_modules."numpy"]
  ignore_errors = true